# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
"""Assemble a ported ADK project on disk: scaffold it with agents-cli, write the
backend .env, and drop the generated app/ files in."""

from __future__ import annotations

import re
import shutil
from pathlib import Path

from app import acli, codegen, config, intake
from app.schemas import PortedFile


def _ported_env() -> str:
    """The `.env` written into every generated project.

    It mirrors whichever backend Rosetta itself is using, so a port you just
    watched being built keeps working when you `cd` into it and run it yourself.

    NO SECRET IS EVER WRITTEN HERE. On the Gemini API backend the key is left in
    the environment: Rosetta launches the ported agent's `adk api_server` as a
    child process without an `env=` override, so the child inherits the key; run
    standalone, it picks up the key from your own shell. That keeps a generated
    project safe to copy, zip or commit.
    """
    header = (
        "# Generated by Rosetta.\n"
        f"# Backend: {config.BACKEND_NAME}. Model: {config.MODEL_NAME}.\n"
    )
    # The generated project's own app/config.py selects the backend; this file
    # only carries the settings a human may want to change.
    if config.USE_AGENT_PLATFORM:
        return header + (
            "# Uses Application Default Credentials — run `gcloud auth application-default login`.\n"
            f"GOOGLE_CLOUD_PROJECT={config.PROJECT_ID}\n"
            f"GOOGLE_CLOUD_LOCATION={config.LOCATION}\n"
            f"MODEL_SMART={config.MODEL_SMART}\n"
            f"MODEL_FAST={config.MODEL_FAST}\n"
        )
    return header + (
        "# Needs GOOGLE_API_KEY in the environment. It is deliberately NOT written\n"
        "# here, so this project stays safe to copy or commit. Inherited from\n"
        "# Rosetta when it launches this agent; export it yourself to run standalone:\n"
        "#   export GOOGLE_API_KEY=...   # https://aistudio.google.com/apikey\n"
        f"MODEL_SMART={config.MODEL_SMART}\n"
        f"MODEL_FAST={config.MODEL_FAST}\n"
    )


def scaffold_project(name: str) -> tuple[Path, acli.Run]:
    """Fresh-scaffold workspace/ported/<name> via agents-cli. Returns (project, run)."""
    project = intake.PORTED_DIR / name
    if project.exists():
        shutil.rmtree(project)
    run = acli.scaffold_create(name, intake.PORTED_DIR)
    return project, run


def write_env(project: Path) -> None:
    # Built per call, not at import: the backend is resolved from the environment.
    (project / ".env").write_text(_ported_env(), encoding="utf-8")


def apply_files(project: Path, files: list[PortedFile]) -> list[str]:
    """Write the generated app/ files over the scaffold."""
    return codegen.write_files(project, files)


# Name[extras][version-specifier] only. Deliberately strict: no URLs, no VCS refs,
# no local paths, no shell metacharacters — the contents come from a model, and
# `uv add` would happily install from a URL. This keeps it to plain PyPI names.
_REQ_RE = re.compile(
    r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}"  # package name
    r"(\[[A-Za-z0-9,._-]{1,64}\])?"  # optional extras
    r"([<>=!~]=?[0-9A-Za-z.*+-]{1,32}(,[<>=!~]=?[0-9A-Za-z.*+-]{1,32})*)?$"  # optional pins
)
MAX_EXTRA_DEPS = 5
DEPS_FILE = "rosetta-deps.txt"


def read_extra_deps(project: Path) -> tuple[list[str], list[str]]:
    """Parse + validate the generator's optional `rosetta-deps.txt` manifest.

    Returns (accepted, rejected). The file is consumed (deleted) so it never ends
    up in the delivered project and cannot be re-applied on a repair pass.
    """
    f = project / DEPS_FILE
    if not f.exists():
        return [], []
    try:
        raw = f.read_text(encoding="utf-8")
    finally:
        f.unlink(missing_ok=True)

    accepted: list[str] = []
    rejected: list[str] = []
    for line in raw.splitlines():
        req = line.split("#", 1)[0].strip()
        if not req:
            continue
        if _REQ_RE.match(req) and len(accepted) < MAX_EXTRA_DEPS:
            accepted.append(req)
        else:
            rejected.append(req)
    return accepted, rejected


def apply_extra_deps(project: Path) -> tuple[list[str], list[str], str]:
    """Install the validated extra deps. Returns (added, rejected, error).

    Best-effort: a failed `uv add` is reported, not fatal — the port may still
    import and run, and the verify/self-heal loop gets the real error either way.
    """
    accepted, rejected = read_extra_deps(project)
    if not accepted:
        return [], rejected, ""
    r = acli.uv_add(project, accepted)
    return (
        (accepted if r.ok else []),
        rejected,
        ("" if r.ok else (r.err or r.out)[-400:]),
    )


def merge_files(current: list[PortedFile], patch: list[PortedFile]) -> list[PortedFile]:
    """Overlay fixer output onto the current fileset (by path)."""
    by_path = {f.path: f for f in current}
    for f in patch:
        by_path[f.path] = f
    return list(by_path.values())


def acli_install_or_sync(project: Path) -> acli.Run:
    """Install the ported project's deps: prefer `agents-cli install`, fall back to
    `uv sync` (both create/populate the project's own venv)."""
    r = acli.install(project)
    if not r.ok:
        r = acli.uv_sync(project)
    return r
