steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/livewire-backend', '.']
  dir: 'server'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/livewire-backend']

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'livewire-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/livewire-backend'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8081'
  - '--set-env-vars'
  - 'PROJECT_ID=${PROJECT_ID},LOG_LEVEL=INFO'
  - '--service-account'
  - 'livewire-backend@${PROJECT_ID}.iam.gserviceaccount.com'

images:
- 'gcr.io/$PROJECT_ID/livewire-backend' 