version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/gemini/sample-apps/genwealth"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "maven"
    directory: "/gemini/sample-apps/genwealth"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
