exclude = [ 
    'https://fonts.gstatic.com/',
    'https://fonts.googleapis.com/',
    'http://go/github',
    'http://go/github-googlecloudplatform',
    'https://medium.com/',
]
exclude_path = [
    ".github/actions/spelling",
    "conversation/chat-app/src/app.html",
    "gemini/sample-apps/photo-discovery/app/web/index.html",
    "gemini/sample-apps/genwealth/ui/src/app/research",
    "search/web-app/templates",
]

max_retries = 0
