apiVersion: v1
kind: Service
metadata:
  name: fixmycar-frontend
spec:
  type: LoadBalancer
  selector:
    app: fixmycar-frontend
  ports:
    - name: fixmycar-frontend-port
      protocol: TCP
      port: 80
      targetPort: 8501
