blank_issues_enabled: false
contact_links:
  - name: Google Gen AI Python SDK
    url: https://github.com/googleapis/python-genai
    about: For issues with the Google Gen AI Python SDK, please report in the googleapis/python-genai repository.
  - name: Vertex AI Python SDK
    url: https://github.com/googleapis/python-aiplatform
    about: For issues with the Vertex AI Python SDK, please report in the googleapis/python-aiplatform repository.
  - name: Google AI Gemini API
    url: https://github.com/google-gemini
    about: This repository is for Generative AI with Vertex AI on Google Cloud, not the Google AI Gemini/PaLM APIs. For issues with the Google AI Gemini API, report them in the appropriate repository in the google-gemini GitHub organization.
  - name: Google Cloud Support
    url: https://cloud.google.com/support
    about: If you have a support contract with Google, please create a case in the support console instead of filing on GitHub. This will ensure a timely response.
  - name: Stack Overflow - Google Cloud Collective
    url: https://stackoverflow.com/collectives/google-cloud
    about: A collective for developers who utilize Google Cloud's infrastructure and platform capabilities. This collective is organized and managed by the Stack Overflow community.
  - name: Google Cloud Skills Boost (Qwiklabs) Support
    url: https://support.google.com/qwiklabs/answer/10702448
    about: For issues with Qwiklabs, such as progress not updating, please contact Qwiklabs support.
