config = {
    "PROJECT_ID": "teamindrdhanush",
    "LOCATION": "us-central1",
    "gemini_parameters": {
        "max_output_tokens": 1024,
        "temperature": 0.05,
        "top_p": 0.7,
        "top_k": 20,
    },
    "MIME_TYPE_PDF": "application/pdf",
    "MIME_TYPE_PNG": "image/png",
    "text_bison_parameters": {
        "max_output_tokens": 2048,
        "temperature": 0.05,
        "top_p": 0.8,
        "top_k": 40,
    },
    "company_email": "teamkavachinsurance@gmail.com",
    "mail_password": "frpx qtau sxfg gjyn",
    "CALENDAR_SCOPE": "https://www.googleapis.com/auth/calendar",
    "EMAIL_SCOPE": "https://www.googleapis.com/auth/script.projects",
    "MAIL_TRIAL_SCOPE": "https://mail.google.com/",
    "text_bison_model": "text-bison-32k",
    "gemini_model": "gemini-pro",
}
