title = "gitleaks config"

[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[rules]]
  id = "aws-access-token"
  description = "AWS Access Token"
  regex = '''AKIA[0-9A-Z]{16}'''
  [rules.allowlist]
    paths = [
      "gemini/use-cases/education/ai_quick_build_experience_backend.ipynb"
    ]
