[flake8]
ignore = ["E501", "E402"]

[mypy]
ignore_missing_imports = true  # Effectively ignores "import-not-found"

[pylint]
disable = ["line-too-long", "missing-module-docstring", "import-error", "wrong-import-position", "ungrouped-imports"]

[ruff]
ignore = ["E402"]
