// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * The single source of truth for Gemini Live Studio design tokens.
 *
 * - `tokens.css` (generated by `npm run tokens`, checked by a unit test)
 *   turns these into `--ga-*` CSS custom properties per theme.
 * - `tailwind.config.ts` maps every colour to `rgb(var(--ga-color-*) / <alpha>)`,
 *   so utility classes such as `bg-primary/10` keep working and follow the
 *   active theme.
 * - Canvas / JS code reads colours at runtime with `readColorToken()`.
 *
 * Themes are selected with `data-theme="light" | "dark" | "system"` on
 * `<html>` (or any ancestor). With no attribute the light theme applies.
 *
 * This module must stay free of side effects and imports so that Node scripts
 * and the Tailwind config can load it directly.
 */

export const lightColors = {
  /** Brand blue: solid fills and accents (buttons, sidebar, focus rings). */
  primary: '#4285F4',
  'primary-hover': '#3367D6',
  /**
   * Primary-coloured text and links. #1a5fc8 (not the proposed #1967d2, which
   * drops to 4.2:1 on surface-container-highest) meets AA on every surface:
   * 5.97:1 on white, 4.63:1 on surface-container-highest.
   */
  'primary-text': '#1a5fc8',
  'on-primary': '#ffffff',
  'primary-container': '#D2E3FC',
  'on-primary-container': '#001a41',
  'primary-fixed': '#d8e2ff',
  'primary-fixed-dim': '#adc6ff',
  'on-primary-fixed': '#001a41',
  'on-primary-fixed-variant': '#004494',

  secondary: '#495e89',
  'on-secondary': '#ffffff',
  'secondary-container': '#b7ccfd',
  'on-secondary-container': '#2c4169',
  'secondary-fixed': '#d8e2ff',
  'secondary-fixed-dim': '#b1c6f7',
  'on-secondary-fixed': '#001a41',
  'on-secondary-fixed-variant': '#31466f',

  tertiary: '#8f4a00',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#b35e00',
  'on-tertiary-container': '#fffbff',
  'tertiary-fixed': '#ffdcc4',
  'tertiary-fixed-dim': '#ffb780',
  'on-tertiary-fixed': '#2f1400',
  'on-tertiary-fixed-variant': '#6f3800',

  error: '#ba1a1a',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#93000a',

  success: '#16a34a',
  'on-success': '#ffffff',
  'success-container': '#dcfce7',
  'on-success-container': '#14532d',

  background: '#f9f9ff',
  'on-background': '#191b22',
  surface: '#f9f9ff',
  'surface-bright': '#f9f9ff',
  'surface-dim': '#d8d9e3',
  'surface-variant': '#e1e2eb',
  'on-surface': '#191b22',
  'on-surface-variant': '#424753',

  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#f2f3fd',
  'surface-container': '#ecedf7',
  'surface-container-high': '#e7e7f1',
  'surface-container-highest': '#e1e2eb',

  outline: '#727785',
  'outline-variant': '#c2c6d5',

  'inverse-surface': '#2e3038',
  'inverse-on-surface': '#eff0fa',
  'inverse-primary': '#adc6ff',
  'surface-tint': '#005ac1',

  /** Translucent overlay base for captions over imagery and video. */
  scrim: '#000000',

  /**
   * Theme-aware soft accent for selected tiles, icon chips and tonal hovers.
   * Unlike the M3 *-fixed tokens (identical in both themes), these flip in dark.
   */
  'primary-soft': '#d8e2ff',
  'on-primary-soft': '#001a41',
  /** App navigation (sidebar, mobile header): brand blue in light, a dark surface in dark. */
  nav: '#4285F4',
  'on-nav': '#ffffff',
  /** Backdrop behind camera / video previews: dark in both themes. */
  'media-backdrop': '#2e3038',

  /** Live audio visualizer orb (canvas). Same in both themes: the orb is self-lit. */
  'viz-speaking-highlight': '#38bdf8',
  'viz-speaking': '#006493',
  'viz-speaking-deep': '#004b70',
  'viz-idle-highlight': '#0284c7',
  'viz-idle-deep': '#00344f',
  'viz-listening-highlight': '#fb7185',
  'viz-listening': '#ba1a1a',
  'viz-listening-accent': '#f97316',
  'viz-listening-deep': '#7f1d1d',
  'viz-bar-idle': '#71787e',
  'viz-night': '#0f172a',
} as const;

export type ColorToken = keyof typeof lightColors;

/** Dark theme. Must define exactly the same keys as `lightColors`. */
export const darkColors: Record<ColorToken, string> = {
  primary: '#adc6ff',
  'primary-hover': '#c7d8ff',
  'primary-text': '#adc6ff',
  'on-primary': '#002e69',
  'primary-container': '#004494',
  'on-primary-container': '#d8e2ff',
  'primary-fixed': '#d8e2ff',
  'primary-fixed-dim': '#adc6ff',
  'on-primary-fixed': '#001a41',
  'on-primary-fixed-variant': '#004494',

  secondary: '#b1c6f7',
  'on-secondary': '#192f57',
  'secondary-container': '#31466f',
  'on-secondary-container': '#d8e2ff',
  'secondary-fixed': '#d8e2ff',
  'secondary-fixed-dim': '#b1c6f7',
  'on-secondary-fixed': '#001a41',
  'on-secondary-fixed-variant': '#31466f',

  tertiary: '#ffb780',
  'on-tertiary': '#4e2600',
  'tertiary-container': '#6f3800',
  'on-tertiary-container': '#ffdcc4',
  'tertiary-fixed': '#ffdcc4',
  'tertiary-fixed-dim': '#ffb780',
  'on-tertiary-fixed': '#2f1400',
  'on-tertiary-fixed-variant': '#6f3800',

  error: '#ffb4ab',
  'on-error': '#690005',
  'error-container': '#93000a',
  'on-error-container': '#ffdad6',

  success: '#4ade80',
  'on-success': '#053317',
  'success-container': '#14532d',
  'on-success-container': '#dcfce7',

  background: '#111318',
  'on-background': '#e2e2e9',
  surface: '#111318',
  'surface-bright': '#37393e',
  'surface-dim': '#111318',
  'surface-variant': '#44474f',
  'on-surface': '#e2e2e9',
  'on-surface-variant': '#c4c6d0',

  'surface-container-lowest': '#0c0e13',
  'surface-container-low': '#191c20',
  'surface-container': '#1d2024',
  'surface-container-high': '#282a2f',
  'surface-container-highest': '#33353a',

  outline: '#8e9099',
  'outline-variant': '#44474f',

  'inverse-surface': '#e2e2e9',
  'inverse-on-surface': '#2e3038',
  'inverse-primary': '#005ac1',
  'surface-tint': '#adc6ff',

  scrim: '#000000',
  'primary-soft': '#004494',
  'on-primary-soft': '#d8e2ff',
  nav: '#191c20',
  'on-nav': '#e2e2e9',
  'media-backdrop': '#0c0e13',

  'viz-speaking-highlight': '#38bdf8',
  'viz-speaking': '#006493',
  'viz-speaking-deep': '#004b70',
  'viz-idle-highlight': '#0284c7',
  'viz-idle-deep': '#00344f',
  'viz-listening-highlight': '#fb7185',
  'viz-listening': '#ba1a1a',
  'viz-listening-accent': '#f97316',
  'viz-listening-deep': '#7f1d1d',
  'viz-bar-idle': '#71787e',
  'viz-night': '#0f172a',
};

export const fontTokens = {
  sans: "'Google Sans Flex', -apple-system, BlinkMacSystemFont, sans-serif",
  mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
} as const;

export type GaTone = 'neutral' | 'primary' | 'success' | 'danger';

export type GaTheme = 'light' | 'dark' | 'system';

/** CSS custom property name for a colour token. */
export function colorVar(token: ColorToken): string {
  return `--ga-color-${token}`;
}

/** "#4285F4" -> "66 133 244" (space-separated channels for rgb(var() / a)). */
export function hexToChannels(hex: string): string {
  const h = hex.replace('#', '');
  const full = h.length === 3 ? [...h].map((c) => c + c).join('') : h;
  const n = Number.parseInt(full, 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
}

function declarations(
  colors: Record<ColorToken, string>,
  indent: string,
): string {
  return (Object.keys(colors) as ColorToken[])
    .map((k) => `${indent}${colorVar(k)}: ${hexToChannels(colors[k])};`)
    .join('\n');
}

/** Generates the contents of `src/theme/tokens.css`. */
export function tokenCss(): string {
  return `/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* GENERATED by \`npm run tokens\` from src/theme/tokens.ts. Do not edit. */
/* Colours are space-separated RGB channels: use rgb(var(--ga-color-x) / <alpha>). */

:root,
[data-theme='light'] {
  color-scheme: light;
  --ga-font-sans: ${fontTokens.sans};
  --ga-font-mono: ${fontTokens.mono};
${declarations(lightColors, '  ')}
}

[data-theme='dark'] {
  color-scheme: dark;
${declarations(darkColors, '  ')}
}

@media (prefers-color-scheme: dark) {
  [data-theme='system'] {
    color-scheme: dark;
${declarations(darkColors, '    ')}
  }
}
`;
}

/**
 * Reads a colour token from the computed style of `el` (so it follows the
 * active theme) and returns it as an `rgb()`/`rgba()` string for canvas use.
 */
export function readColorToken(
  el: Element,
  token: ColorToken,
  alpha = 1,
): string {
  return colorTokenReader(el)(token, alpha);
}

/**
 * Like `readColorToken`, but resolves the computed style once and returns a
 * reader, for code that needs many colours per frame (canvas render loops).
 */
export function colorTokenReader(
  el: Element,
): (token: ColorToken, alpha?: number) => string {
  const style = getComputedStyle(el);
  return (token, alpha = 1) => {
    const channels = style.getPropertyValue(colorVar(token)).trim();
    return `rgb(${channels || hexToChannels(lightColors[token])} / ${alpha})`;
  };
}

/** Applies a theme to the document root. */
export function setTheme(
  theme: GaTheme,
  root: HTMLElement = document.documentElement,
): void {
  root.dataset.theme = theme;
}
