version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkedin-profile-image-generation-backend
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    env_file:
      - .local.env
    environment:
      - FRONTEND_URL=http://localhost:4200
    restart: unless-stopped
